#cloud-config
package_upgrade: true
packages:
  - awscli
  - curl
yum_repos:
  # The name of the repository
  wireguard:
    # Any repository configuration options
    # See: man yum.conf
    name: Wireguard by JDOSS
    baseurl: https://download.copr.fedorainfracloud.org/results/jdoss/wireguard/epel-7-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/jdoss/wireguard/pubkey.gpg
    enabled: true
    failovermethod: priority
    gpgcheck: true
    repo_gpgcheck: false
    enabled_metadata: true
    skip_if_unavailable: true

runcmd:
  - echo ECS_CLUSTER=${cluster_name} > /etc/ecs/ecs.config
  # install wireguard module
  - yum install wireguard-dkms wireguard-tools -y

  # enable module
  - modprobe wireguard
  - modprobe iptable_nat
  - modprobe ip6table_nat

  - echo "wireguard" > /etc/modules-load.d/wireguard.conf
  - echo "iptable_nat" > /etc/modules-load.d/iptable_nat.conf
  - echo "ip6table_nat" > /etc/modules-load.d/ip6table_nat.conf

    # Check if systemd-modules-load service is active.
  - systemctl status systemd-modules-load.service

    # Enable IP forwarding.
  - sysctl -w net.ipv4.ip_forward=1
  - sysctl net.ipv4.conf.all.forwarding=1 | tee -a /etc/sysctl.d/forwarding.conf

